// Master asset registry for the Room Designer.
//
// STAGE 0 shape preserved. STAGE 1 adds optional license/source fields and a
// sibling MATERIAL_REGISTRY in ./material-registry.ts. Runtime path resolution
// (reading room-designer-assets/manifest.json from Supabase Storage) lands in
// Stage 2 via a getResolvedAsset(id) helper.
//
// STAGE 2 TODO: src/app/api/assets/route.ts returns this registry with
// modelPath/thumbnailPath=null. Stage 2 must fetch manifest.json from Supabase
// and merge the GLB URLs into the response (or do the merge client-side).
// `force-static` was removed in Stage 1.5 so the route can run dynamically
// when the merge lands.

import type { AssetCategory } from "@/components/room-designer/types";

export interface Asset {
    id: string;
    name: string;
    category: AssetCategory;
    subcategory: string;
    modelPath: string | null; // Stage 0: null (box fallback). Stage 2: Supabase public URL.
    thumbnailPath: string | null; // Stage 0: null (UI renders category icon fallback).
    dimensions: { width: number; height: number; depth: number }; // meters
    tags: string[];
    license?: "CC0" | "CC-BY" | "MIT"; // populated by manifest lookup in Stage 2
    source?: string; // e.g. "polyhaven:modern_armchair_01"
}

// Dimensions drawn from standard millwork/appliance catalogs, converted to meters.
export const ASSET_REGISTRY: Asset[] = [
    // ───────── Cabinets (10) — base/standard heights: 34.5" ≈ 0.876 m, wall: 30" ≈ 0.762 m, tall: 84" ≈ 2.134 m
    {
        id: "base-cabinet-24",
        name: 'Base Cabinet 24"',
        category: "cabinet",
        subcategory: "base",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.6096, height: 0.876, depth: 0.6096 },
        tags: ["kitchen", "base", "single-door"],
    },
    {
        id: "base-cabinet-36",
        name: 'Base Cabinet 36"',
        category: "cabinet",
        subcategory: "base",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.9144, height: 0.876, depth: 0.6096 },
        tags: ["kitchen", "base", "double-door"],
    },
    {
        id: "wall-cabinet-30",
        name: 'Wall Cabinet 30"',
        category: "cabinet",
        subcategory: "wall",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.762, height: 0.762, depth: 0.3048 },
        tags: ["kitchen", "wall"],
    },
    {
        id: "corner-cabinet",
        name: "Corner Lazy Susan",
        category: "cabinet",
        subcategory: "corner",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.9144, height: 0.876, depth: 0.9144 },
        tags: ["kitchen", "corner", "lazy-susan"],
    },
    {
        id: "island-cabinet",
        name: 'Island Cabinet 48"',
        category: "cabinet",
        subcategory: "island",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 1.2192, height: 0.876, depth: 0.9144 },
        tags: ["kitchen", "island"],
    },
    {
        id: "pantry-cabinet",
        name: "Pantry Cabinet",
        category: "cabinet",
        subcategory: "tall",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.6096, height: 2.1336, depth: 0.6096 },
        tags: ["kitchen", "pantry", "tall"],
    },
    {
        id: "open-shelf",
        name: "Open Floating Shelf",
        category: "cabinet",
        subcategory: "shelf",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.9144, height: 0.0381, depth: 0.254 },
        tags: ["kitchen", "shelf", "open"],
    },
    {
        id: "drawer-base",
        name: "4-Drawer Base",
        category: "cabinet",
        subcategory: "base",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.762, height: 0.876, depth: 0.6096 },
        tags: ["kitchen", "base", "drawers"],
    },
    {
        id: "sink-base-36",
        name: 'Sink Base 36"',
        category: "cabinet",
        subcategory: "base",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.9144, height: 0.876, depth: 0.6096 },
        tags: ["kitchen", "base", "sink"],
    },
    {
        id: "glass-door-cabinet",
        name: "Glass Door Wall Cabinet",
        category: "cabinet",
        subcategory: "wall",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.762, height: 0.762, depth: 0.3048 },
        tags: ["kitchen", "wall", "glass"],
    },

    // ───────── Appliances (10)
    {
        id: "refrigerator-french",
        name: "French Door Refrigerator",
        category: "appliance",
        subcategory: "refrigerator",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.9144, height: 1.778, depth: 0.762 },
        tags: ["kitchen", "fridge"],
    },
    {
        id: "stove-range-30",
        name: '30" Gas Range',
        category: "appliance",
        subcategory: "range",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.762, height: 0.9144, depth: 0.6604 },
        tags: ["kitchen", "stove", "gas"],
    },
    {
        id: "oven-wall",
        name: "Wall Oven",
        category: "appliance",
        subcategory: "oven",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.762, height: 0.6604, depth: 0.6096 },
        tags: ["kitchen", "oven", "wall"],
    },
    {
        id: "dishwasher",
        name: "Dishwasher",
        category: "appliance",
        subcategory: "dishwasher",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.6096, height: 0.8509, depth: 0.6096 },
        tags: ["kitchen", "dishwasher"],
    },
    {
        id: "microwave-over-range",
        name: "Over-Range Microwave",
        category: "appliance",
        subcategory: "microwave",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.762, height: 0.4318, depth: 0.4064 },
        tags: ["kitchen", "microwave"],
    },
    {
        id: "washer",
        name: "Front Load Washer",
        category: "appliance",
        subcategory: "laundry",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.686, height: 0.965, depth: 0.8128 },
        tags: ["laundry", "washer"],
    },
    {
        id: "dryer",
        name: "Front Load Dryer",
        category: "appliance",
        subcategory: "laundry",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.686, height: 0.965, depth: 0.8128 },
        tags: ["laundry", "dryer"],
    },
    {
        id: "range-hood",
        name: "Range Hood",
        category: "appliance",
        subcategory: "hood",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.762, height: 0.1524, depth: 0.508 },
        tags: ["kitchen", "hood"],
    },
    {
        id: "wine-refrigerator",
        name: "Wine Fridge",
        category: "appliance",
        subcategory: "refrigerator",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.6096, height: 0.876, depth: 0.6096 },
        tags: ["kitchen", "wine"],
    },
    {
        id: "ice-maker",
        name: "Undercounter Ice Maker",
        category: "appliance",
        subcategory: "icemaker",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.381, height: 0.876, depth: 0.6096 },
        tags: ["kitchen", "ice"],
    },

    // ───────── Fixtures (8)
    {
        id: "kitchen-sink-farmhouse",
        name: "Farmhouse Sink",
        category: "fixture",
        subcategory: "sink",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.762, height: 0.2794, depth: 0.5588 },
        tags: ["kitchen", "sink"],
    },
    {
        id: "bathroom-sink-vessel",
        name: "Vessel Sink",
        category: "fixture",
        subcategory: "sink",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.4572, height: 0.1524, depth: 0.4572 },
        tags: ["bathroom", "sink"],
    },
    {
        id: "toilet-standard",
        name: "Standard Toilet",
        category: "fixture",
        subcategory: "toilet",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.4318, height: 0.762, depth: 0.7112 },
        tags: ["bathroom", "toilet"],
    },
    {
        id: "bathtub-freestanding",
        name: "Freestanding Soaking Tub",
        category: "fixture",
        subcategory: "tub",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 1.6764, height: 0.6096, depth: 0.8128 },
        tags: ["bathroom", "tub"],
    },
    {
        id: "shower-base",
        name: "Shower Base",
        category: "fixture",
        subcategory: "shower",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.9144, height: 0.1524, depth: 0.9144 },
        tags: ["bathroom", "shower"],
    },
    {
        id: "vanity-double",
        name: 'Double Vanity 60"',
        category: "fixture",
        subcategory: "vanity",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 1.524, height: 0.8509, depth: 0.5588 },
        tags: ["bathroom", "vanity"],
    },
    {
        id: "towel-bar",
        name: 'Towel Bar 24"',
        category: "fixture",
        subcategory: "accessory",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.6096, height: 0.0508, depth: 0.0762 },
        tags: ["bathroom", "towel"],
    },
    {
        id: "bathroom-mirror",
        name: "Framed Bathroom Mirror",
        category: "fixture",
        subcategory: "mirror",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.9144, height: 0.762, depth: 0.0381 },
        tags: ["bathroom", "mirror"],
    },

    // ───────── Windows (5)
    {
        id: "window-single-hung",
        name: "Single Hung Window",
        category: "window",
        subcategory: "hung",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.9144, height: 1.2192, depth: 0.1016 },
        tags: ["window"],
    },
    {
        id: "window-double-hung",
        name: "Double Hung Window",
        category: "window",
        subcategory: "hung",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.9144, height: 1.524, depth: 0.1016 },
        tags: ["window"],
    },
    {
        id: "window-bay",
        name: "Bay Window",
        category: "window",
        subcategory: "bay",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 1.8288, height: 1.524, depth: 0.4572 },
        tags: ["window", "bay"],
    },
    {
        id: "window-casement",
        name: "Casement Window",
        category: "window",
        subcategory: "casement",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.6096, height: 1.2192, depth: 0.1016 },
        tags: ["window"],
    },
    {
        id: "window-skylight",
        name: "Skylight",
        category: "window",
        subcategory: "skylight",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.6096, height: 0.05, depth: 0.9144 },
        tags: ["window", "skylight"],
    },

    // ───────── Doors (4)
    {
        id: "door-single",
        name: 'Single Door 32"',
        category: "door",
        subcategory: "single",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.8128, height: 2.032, depth: 0.0508 },
        tags: ["door"],
    },
    {
        id: "door-double",
        name: "Double Entry Door",
        category: "door",
        subcategory: "double",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 1.8288, height: 2.032, depth: 0.0508 },
        tags: ["door", "entry"],
    },
    {
        id: "door-sliding",
        name: "Sliding Barn Door",
        category: "door",
        subcategory: "sliding",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.9144, height: 2.032, depth: 0.0381 },
        tags: ["door", "barn"],
    },
    {
        id: "door-pocket",
        name: "Pocket Door",
        category: "door",
        subcategory: "pocket",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.762, height: 2.032, depth: 0.0381 },
        tags: ["door", "pocket"],
    },

    // ───────── Lighting (5) — optional category, Stage 1.5 addition.
    // Dimensions are Stage 0 AABB estimates in meters. Stage 2 swaps to
    // the real GLB bounding box via the asset-resolve pipeline.
    {
        id: "ceiling-light-1",
        name: "Flush Mount Ceiling Light",
        category: "lighting",
        subcategory: "ceiling",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.35, height: 0.15, depth: 0.35 },
        tags: ["light", "ceiling", "flush-mount"],
    },
    {
        id: "ceiling-light-2",
        name: "Pendant Ceiling Light",
        category: "lighting",
        subcategory: "ceiling",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.30, height: 0.45, depth: 0.30 },
        tags: ["light", "ceiling", "pendant"],
    },
    {
        id: "chandelier",
        name: "Chandelier",
        category: "lighting",
        subcategory: "ceiling",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.70, height: 0.80, depth: 0.70 },
        tags: ["light", "ceiling", "chandelier"],
    },
    {
        id: "floor-lamp",
        name: "Floor Lamp",
        category: "lighting",
        subcategory: "floor",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.40, height: 1.60, depth: 0.40 },
        tags: ["light", "floor", "lamp"],
    },
    {
        id: "desk-lamp",
        name: "Desk Lamp",
        category: "lighting",
        subcategory: "table",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.20, height: 0.50, depth: 0.25 },
        tags: ["light", "table", "lamp"],
    },

    // ───────── Plants (3) — optional category, Stage 1.5 addition.
    {
        id: "houseplant-small",
        name: "Small Houseplant",
        category: "plants",
        subcategory: "table",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.30, height: 0.40, depth: 0.30 },
        tags: ["plant", "small", "decor"],
    },
    {
        id: "houseplant-medium",
        name: "Medium Houseplant",
        category: "plants",
        subcategory: "floor",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.45, height: 0.80, depth: 0.45 },
        tags: ["plant", "medium", "decor"],
    },
    {
        id: "houseplant-large",
        name: "Large Houseplant",
        category: "plants",
        subcategory: "floor",
        modelPath: null,
        thumbnailPath: null,
        dimensions: { width: 0.60, height: 1.40, depth: 0.60 },
        tags: ["plant", "large", "decor"],
    },
];

export const ASSETS_BY_CATEGORY: Record<AssetCategory, Asset[]> = {
    cabinet: ASSET_REGISTRY.filter((a) => a.category === "cabinet"),
    appliance: ASSET_REGISTRY.filter((a) => a.category === "appliance"),
    fixture: ASSET_REGISTRY.filter((a) => a.category === "fixture"),
    window: ASSET_REGISTRY.filter((a) => a.category === "window"),
    door: ASSET_REGISTRY.filter((a) => a.category === "door"),
    lighting: ASSET_REGISTRY.filter((a) => a.category === "lighting"),
    plants: ASSET_REGISTRY.filter((a) => a.category === "plants"),
};

export function getAsset(id: string): Asset | undefined {
    return ASSET_REGISTRY.find((a) => a.id === id);
}

// Category → base hex color used for Stage 0 placeholder boxes.
export const CATEGORY_COLORS: Record<AssetCategory, string> = {
    cabinet: "#c9a06b",
    appliance: "#8a8f97",
    fixture: "#d4d8de",
    window: "#9cc7e8",
    door: "#6b4f3a",
    lighting: "#f5c542",
    plants: "#5a9b56",
};
