ALTER TABLE "ChangeOrder" ADD COLUMN IF NOT EXISTS "approvalSource" TEXT;
ALTER TABLE "ChangeOrder" ADD COLUMN IF NOT EXISTS "approvalMethod" TEXT;
ALTER TABLE "ChangeOrder" ADD COLUMN IF NOT EXISTS "approvalNote" TEXT;
