import test from 'node:test';
import assert from 'node:assert/strict';
import { fixture } from './fixtures/legacy-recovery-fixture';
import { loadRecoverySnapshot, writeRecovery } from '../src/lib/legacy-affidavit-recovery-store';
import { stableRecoveryDigest } from '../src/lib/legacy-affidavit-recovery-proof';
function harness(){const {packet,canonical}=fixture();const queries:any[]=[];const writes:any[]=[];let extra:any[]=[];
 const db:any={bankLine:{findUnique:async()=>({...canonical,updatedAt:'2026-08-20T00:00:00Z'}),findMany:async(args:any)=>{queries.push(['competing',args]);return [{id:canonical.id,rawDescriptor:canonical.rawDescriptor},...extra];}},reviewIssue:{findUnique:async()=>({id:'issue-1',version:3,displayDetails:JSON.stringify({cards:[{n:1,threadName:'existingThread'}]}),clearedAt:null}),findMany:async()=>[],updateMany:async(args:any)=>{writes.push(['cas',args]);return{count:1};}},receiptMemoArtifact:{findMany:async(args:any)=>{queries.push(['artifacts',args]);return[];},count:async(args:any)=>{queries.push(['unknownCount',args]);return 0;},create:async(args:any)=>{writes.push(['artifact',args]);return args.data;}},reviewAlertEpisode:{updateMany:async(args:any)=>{writes.push(['episodes',args]);return{count:0};}},$queryRaw:async(strings:any,...values:any[])=>{writes.push(['epoch',strings.join('?'),values]);return[];},$executeRaw:async(strings:any)=>{writes.push(['raw',strings.join('?')]);return 0;}};
 return{packet,canonical,db,queries,writes,setExtra:(rows:any[])=>{extra=rows;}};}
test('store uses card marker, not authorization time, and global hashless inventory',async()=>{const h=harness();const s=await loadRecoverySnapshot(h.db,h.packet);assert.equal(s.identityConflict,false);assert.deepEqual(h.queries.find(x=>x[0]==='unknownCount')[1],{where:{pdfSha256:null}});assert.equal(h.queries.find(x=>x[0]==='competing')[1].where.postedDate,undefined);});
test('same source identity on another canonical target conflicts',async()=>{const h=harness();h.setExtra([{id:'another-line',rawDescriptor:h.canonical.rawDescriptor}]);assert.equal((await loadRecoverySnapshot(h.db,h.packet)).identityConflict,true);});
test('writer preserves cards and original provenance and uses canonical epoch before CAS',async()=>{const h=harness();const snapshot=await loadRecoverySnapshot(h.db,h.packet);await writeRecovery(h.db,{snapshot,packet:h.packet,pdf:{id:h.packet.pdf.id,sha256:h.packet.pdf.sha256,version:'1',byteLength:1234},planDigest:'c'.repeat(64),recoveredAt:'2026-09-10T00:00:00Z',recoveredBy:'cron-machine'});assert.deepEqual(h.writes.map(x=>x[0]),['epoch','cas','artifact','episodes']);assert.match(h.writes[0][1],/AutomationSetting/);const details=JSON.parse(h.writes[1][1].data.displayDetails);assert.deepEqual(details.cards,[{n:1,threadName:'existingThread'}]);assert.equal(details.signedAt,h.packet.legacy.signedAtVerbatim);const prov=JSON.parse(h.writes[2][1].data.provenanceJson);assert.equal(prov.packetDigest,stableRecoveryDigest(h.packet));assert.deepEqual(prov.packet,h.packet);assert.equal(prov.recoveredBy,'cron-machine');assert.equal(prov.chatVerification,'admin-attested-provider-packet');});
